swagger: "2.0"
info:
  version: "1.0"
  title: "Core APIs (Example)"
  description: Below you will find the different APIs provided by "Core", as a simplified example. Please be aware a valid API-Key and matching GCID is required for all request! 
  
security:
  - ApiKeyAuth: ["abc"]
    GCID: ["def"]
      

paths:
  /loan:
    get:
      description: Get a list of all active Loan IDs for a specified Global Client ID from the Authentication Header
      responses:
        200:
          description: Returns a list of all Loan IDs for "GCID"
          schema:
            type: array
        401:
          $ref: "#/responses/UnauthorizedError"
  
  
  /loan/{loanid}:
    get:
      description: get amount, principal, maturity date, interest and currency of a specific Loan
      parameters:
        - name: loanid
          in: path
          type: string
          required: true
          description: Loan ID for which to request the Loan data
      responses:
        200:
          description: id, amount, principal, maturity date, interest and currency of a specific Loan
          schema:
            type: object
            properties:
              amount:
                type: number
                description: the total amount of the loan
              principal:
                type: number
                description: the amount of the principal, or outstanding amount
              currency:
                type: string
                description: the currency of the amount and principal
              maturity_date:
                type: string
                description: the maturity date of the loan
              period_days:
                type: number
                description: the number of days between the start and the maturity of a loan
              interest:
                type: number
                description: the interest rate used for the loan
        400:
          description: Invalid characters in "id" were provided.
        401:
          $ref: "#/responses/UnauthorizedError"
  
    
  /loan/rollover/{loanid}:
    post:
      description: Simple rollover for a loan on the same conditions
      parameters:
        - name: loanid
          in: path
          type: string
          required: true
          description: Loan ID for which to perform a simple rollover, meaning
            only change the maturity date for the period of the loan
      responses:
        200:
          description: Returns the ID, amount, principal, currency, interest and new maturity date of the rolled-over loan.
          schema:
            type: object
            properties:
              amount:
                type: number
                description: the total amount of the loan
              principal:
                type: number
                description: the amount of the principal, or outstanding amount
              currency:
                type: string
                description: the currency of the amount and principal
              maturity_date:
                type: string
                description: the maturity date of the loan
              period_days:
                type: number
                description: the number of days between the start and the maturity of a loan
              interest:
                type: number
                description: the interest rate used for the loan
        400:
          description: Invalid characters in "loanid" were provided.
        401:
          $ref: "#/responses/UnauthorizedError"

    
  /account:
    get:
      description: get a list of all accounts for a specific Global Client ID
      responses:
        200:
          description: returns a list of all accounts for "gcid"
          schema:
            type: array
            description: an list of all active accounts for "gcid"
        400:
          description: Invalid characters in "gcid" were provided.
        401:
          $ref: "#/responses/UnauthorizedError"
         
  /account/credit_transfer:
    post:
      description: Initiate a credit transfer
      parameters:
        - name: account_number
          in: query
          type: string
          required: true
          description: the originating account number 
        - name: benificiary
          in: query
          type: string
          required: true
          description: the benificiary account number
        - name: currency
          in: query
          type: string
          required: true
          description: currency of the payment transfer
        - name: amount
          in: query
          type: number
          required: true
          description: the amount of the credit transfer
        - name: urgent
          in: query
          type: boolean
          required: false
          description: set to true for urgent payment
      responses:
        200:
          description: returns the status of the credit transfer
          schema:
            type: string
            description: the status of the credit transfer, e.g. "Successful","Insufficient funds" 
        400:
          description: Invalid value in one of the parameters
        401:
          $ref: "#/responses/UnauthorizedError"
          
securityDefinitions:
   # X-API-Key: abcdef12345
   APIKeyAuth:
     type: apiKey
     in: header
     name: X-API-Key
   GCID:
    type: apiKey
    in: header
    name: GCID
     
responses:
  UnauthorizedError:
    description: API key is missing or invalid
    headers:
      WWW_Authenticate:
        type: string